server {
    listen 80;
    server_name _;

    root /var/www/html;

    error_page 503 /maintenance.html;
    location = /maintenance.html {
        internal;
    }

    location = /complete.html {
        try_files /complete.html =404;
    }

    location = /status.css {
        log_not_found off;
        access_log off;
    }

    location = /favicon.ico {
        proxy_pass http://webapp:8000;
        proxy_set_header Host $host;
        log_not_found off;
        access_log off;
    }

    location / {
        if (-f /var/www/html/complete_on) {
            rewrite ^ /complete.html last;
        }

        if (-f /var/www/html/maintenance_on) {
            return 503;
        }

        try_files $uri @proxy;
    }

    location @proxy {
        proxy_pass http://webapp:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}