experiment_name: 1600_1k_30_trial_kepoch_10_10x
trials: 20
number_of_procs: 5
test_storage: test_results
env: minecraft
env_config:
  max_episode_len: 500
  grid:
    height: 10
    width: 10
  lidar:
    range: 5

# --- LLM Curriculum Settings ---
use_llm_curriculum: false
llm_curriculum_iterations: 0
llm_model: null
llm_messages_template: null

# --- Standard Training Settings ---
standard_training_iterations: 1000
standard_training_config:
  episodes_per_evaluation: 3
  episodes_per_iteration: 25
  update_frequency: 1600
  lr_actor: 0.0001
  lr_critic: 0.001
  gamma: 0.99
  K_epochs: 10
  eps_clip: 0.2
  has_continuous_action_space: false
